blueprint:
  name: Hue Wall Switch
  description: Hue Wall Switch single,double and tripple press
  domain: automation
  source_url: https://github.com/ken536/HomeAssistant/
  input:
    switch_device:
      name: Wall Switch Device
      description: "Your Hue wall switch; check Hue integration and/or Hue app if you don't know the name"
      selector:
        device:
          integration: hue
    on_single1_action:
      name: Switch1 - On Single press action
      description: Action to perform when switch 1 is pressed once
      default: []
      selector:
        action:
    on_double1_action:
      name: Switch1 - On Double press Action
      description: Action to perform when switch 1 is pressed twice
      default: []
      selector:
        action:
    on_triple1_action:
      name: Switch1 - On Triple press Action
      description: Action to perform when switch 1 is pressed three times
      default: []
      selector:
        action:
    on_single2_action:
      name: Switch2 - On Single press action
      description: Action to perform when switch 2 is pressed once
      default: []
      selector:
        action:
    on_double2_action:
      name: Switch2 - On Double press Action
      description: Action to perform when switch 2 is pressed twice
      default: []
      selector:
        action:
    on_triple2_action:
      name: Switch1 - On Triple press Action
      description: Action to perform when switch 2 is pressed three times
      default: []
      selector:
        action:



trigger:
  - device_id: !input switch_device
    domain: hue
    platform: device
    type: short_release
    subtype: 1
    id: on short_release1
  - device_id: !input switch_device
    domain: hue
    platform: device
    type: short_release
    subtype: 2
    id: on short_release2


action:
    - wait_for_trigger:
        - platform: device
          device_id: !input switch_device
          type: short_release
          subtype: 1
      timeout:
        milliseconds: 1000
      continue_on_timeout: true
    
    - choose:
        - conditions:
            - condition: template
              value_template: '{{ wait.trigger == none }}'
          sequence:
# single click
            !input on_single1_action
      default:
        - wait_for_trigger:
            - platform: device
              device_id: !input switch_device
              type: short_release
              subtype: 1
          timeout:
            milliseconds: 1000
          continue_on_timeout: true
# double click
        - choose:
            - conditions:
                - condition: template
                  value_template: '{{ wait.trigger == none }}'
              sequence: !input on_double1_action
          default:
# triple click
            !input on_triple1_action

mode: single
        

