blueprint:
  name: Hue Wall Switch
  description: |
    Makes control with Hue Wall Switch possible
  domain: automation
  source_url: https://github.com/ken536/HomeAssistant/
  input:
    switch_device:
      name: Wall Switch Device
      description: "Your Hue wall switch; check Hue integration and/or Hue app if you don't know the name"
      selector:
        device:
          integration: hue
    on_init1:
      name: Switch1 - On Initial Press Action
      description: Action to perform when switch 1 is pressed
      default: []
      selector:
        action:
    on_hold1_action:
      name: Switch1 - On Hold Action
      description: Action to perform when switch 1 is hold
      default: []
      selector:
        action:
    on_short1_action:
      name: Switch1 - On Short Release Action
      description: Action to perform when switch 1 is released after a short period
      default: []
      selector:
        action:
    on_long1_action:
      name: Switch1 - On Long Release Action
      description: Action to perform when switch 1 is released after a long period
      default: []
      selector:
        action:
    on_init2:
      name: Switch2 - On Initial Press Action
      description: Action to perform when switch 1 is pressed
      default: []
      selector:
        action:
    on_hold2_action:
      name: Switch2 - On Hold Action
      description: Action to perform when switch 1 is hold
      default: []
      selector:
        action:
    on_short2_action:
      name: Switch2 - On Short Release Action
      description: Action to perform when switch 1 is released after a short period
      default: []
      selector:
        action:
    on_long2_action:
      name: Switch2 - On Long Release Action
      description: Action to perform when switch 1 is released after a long period
      default: []
      selector:
        action:


mode: single

trigger:
  - device_id: !input switch_device
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    id: on init1
  - device_id: !input switch_device
    domain: hue
    platform: device
    type: repeat
    subtype: 1
    id: on hold1
  - device_id: !input switch_device
    domain: hue
    platform: device
    type: short_release
    subtype: 1
    id: on short1
  - device_id: !input switch_device
    domain: hue
    platform: device
    type: long_release
    subtype: 1
    id: on long1
  - device_id: !input switch_device
    domain: hue
    platform: device
    type: initial_press
    subtype: 2
    id: on init2
  - device_id: !input switch_device
    domain: hue
    platform: device
    type: repeat
    subtype: 2
    id: on hold2
  - device_id: !input switch_device
    domain: hue
    platform: device
    type: short_release
    subtype: 2
    id: on short2
  - device_id: !input switch_device
    domain: hue
    platform: device
    type: long_release
    subtype: 2
    id: on long2

condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: on init1
        sequence: !input on_init1_action
      - conditions:
          - condition: trigger
            id: on hold1
        sequence: !input on_hold1_action
      - conditions:
          - condition: trigger
            id: on short1
        sequence: !input on_short1_action
      - conditions:
          - condition: trigger
            id: on long1
        sequence: !input on_long1_action
      - conditions:
          - condition: trigger
            id: on init2
        sequence: !input on_init2_action
      - conditions:
          - condition: trigger
            id: on hold2
        sequence: !input on_hold2_action
      - conditions:
          - condition: trigger
            id: on short2
        sequence: !input on_short2_action
      - conditions:
          - condition: trigger
            id: on long2
        sequence: !input on_long2_action

    default:
      - service: persistent_notification.create
        data:
          message:
            Hue wall switch ran default event from "choose" action on button press!
            Please check any automations which may not be handling this event!
          notification_id: hue_wall_switch_blueprint
          title: Uncaught Wall Switch Command